{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"proceed"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/openaiclient\/connectionerroraction\/proceed"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/OpenAIClient\/documentation\/OpenAIClient\/ConnectionErrorAction\/proceed","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Specifies that the error should be logged normally and dispatched to the "},{"type":"codeVoice","code":"EventHandler"},{"type":"text","text":". Connection retrying will"},{"type":"text","text":" "},{"type":"text","text":"proceed normally if appropriate."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"proceed"}],"title":"ConnectionErrorAction.proceed","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:12OpenAIClient21ConnectionErrorActionO7proceedyA2CmF","modules":[{"name":"OpenAIClient"}]},"hierarchy":{"paths":[["doc:\/\/OpenAIClient\/documentation\/OpenAIClient","doc:\/\/OpenAIClient\/documentation\/OpenAIClient\/ConnectionErrorAction"]]},"references":{"doc://OpenAIClient/documentation/OpenAIClient/ConnectionErrorAction":{"role":"symbol","title":"ConnectionErrorAction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionErrorAction"}],"abstract":[{"type":"text","text":"Potential actions a "},{"type":"codeVoice","code":"ConnectionErrorHandler"},{"type":"text","text":" can return"}],"identifier":"doc:\/\/OpenAIClient\/documentation\/OpenAIClient\/ConnectionErrorAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConnectionErrorAction"}],"url":"\/documentation\/openaiclient\/connectionerroraction"},"doc://OpenAIClient/documentation/OpenAIClient/ConnectionErrorAction/proceed":{"role":"symbol","title":"ConnectionErrorAction.proceed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"proceed"}],"abstract":[{"type":"text","text":"Specifies that the error should be logged normally and dispatched to the "},{"type":"codeVoice","code":"EventHandler"},{"type":"text","text":". Connection retrying will"},{"type":"text","text":" "},{"type":"text","text":"proceed normally if appropriate."}],"identifier":"doc:\/\/OpenAIClient\/documentation\/OpenAIClient\/ConnectionErrorAction\/proceed","kind":"symbol","type":"topic","url":"\/documentation\/openaiclient\/connectionerroraction\/proceed"},"doc://OpenAIClient/documentation/OpenAIClient":{"role":"collection","title":"OpenAIClient","abstract":[],"identifier":"doc:\/\/OpenAIClient\/documentation\/OpenAIClient","kind":"symbol","type":"topic","url":"\/documentation\/openaiclient"}}}